# Generated by Django 2.1.7 on 2019-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idP', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=100)),
                ('idUsuario', models.CharField(max_length=50)),
            ],
        ),
    ]
